theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
title = "Skyler Lawrence"
baseURL = "https://sjmlawrencegames.com"
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
lastName = "Lawrence"
showContact = false
showBoards = false
phone = "1-708-921-5008"
sections = ["publications", "creations", "contributions", "experience", "skills", "education", "blog"]
profileImage = "img/moonbearportraitcommission3.png"
favicon = "/favicon.ico"
address = "Chicago, IL"
showCertifications = false
showProjects = false
showSocializations = true
firstName = "Skyler"
email = "skylerjmlawrence@gmail.com"
showQr = false
vcardfields = ["name", "image", "org", "email", "workemail", "phone", "url", "title"]

[[params.handles]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/skyler-lawrence-art/"

[[params.handles]]
name = "GitHub"
link = "https://github.com/SJMLawrenceart"

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[params.customSections]

[params.customSections.ham]
name = "Itch.io"
url = "https://sjmlawrenceart.itch.io/"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[mediaTypes]

[mediaTypes."text/vcard"]
suffixes = ["vcf"]

[outputFormats]

[outputFormats.VCard]
mediaType = "text/vcard"
baseName = "contact"
isPlainText = true
notAlternative = true